
server:
  port: 8090


spring:
  datasource:

    url: jdbc:mysql://192.168.220.128:3306/wsm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2B8

    driver-class-name: com.mysql.cj.jdbc.Driver

    username: root

    password: zh13079058260